/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;

import conexion.TabUsu;

/**
 *
 * @author HP
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
       //this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Usuario = new javax.swing.JMenu();
        mostarUsu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mostrarCli = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mostrarCat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mostrarProd = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mostrarEmp = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mostrarVen = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mostrarDv = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mostrarAlmp = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mostrarDis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("COMPRAR");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\portada,Miii.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 390));

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1_Usuario.setText("usuarios");

        mostarUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostarUsu.setText("mostrar usuarios");
        mostarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostarUsuActionPerformed(evt);
            }
        });
        jMenu1_Usuario.add(mostarUsu);

        jMenuBar1.add(jMenu1_Usuario);

        jMenu2.setText("cliente");

        mostrarCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarCli.setText("mostrar cliente");
        mostrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCliActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarCli);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("categoria");

        mostrarCat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarCat.setText("mostrar categoria");
        mostrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCatActionPerformed(evt);
            }
        });
        jMenu1.add(mostrarCat);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("producto");

        mostrarProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarProd.setText("mostrar producto");
        mostrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProdActionPerformed(evt);
            }
        });
        jMenu3.add(mostrarProd);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("empleado");

        mostrarEmp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarEmp.setText("mostrar empleado");
        mostrarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEmpActionPerformed(evt);
            }
        });
        jMenu4.add(mostrarEmp);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("ventas");

        mostrarVen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarVen.setText("mostrar ventas");
        mostrarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarVenActionPerformed(evt);
            }
        });
        jMenu5.add(mostrarVen);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("detalle_venta");

        mostrarDv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarDv.setText("mostrar detalle_venta");
        mostrarDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDvActionPerformed(evt);
            }
        });
        jMenu6.add(mostrarDv);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("almacen_productos");

        mostrarAlmp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarAlmp.setText("mostrar almacen_productos");
        mostrarAlmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlmpActionPerformed(evt);
            }
        });
        jMenu7.add(mostrarAlmp);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("distribuidor");

        mostrarDis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        mostrarDis.setText("mostrar distribuidor");
        mostrarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDisActionPerformed(evt);
            }
        });
        jMenu8.add(mostrarDis);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostarUsuActionPerformed
        // TODO add your handling code here:
        TabUsu MostrarUsu = new TabUsu();
        escritorio.add(MostrarUsu);
        MostrarUsu.show();
    }//GEN-LAST:event_mostarUsuActionPerformed

    private void mostrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCatActionPerformed
        // TODO add your handling code here:
        TabCat Mostrarcat = new TabCat();
        escritorio.add(Mostrarcat);
        Mostrarcat.show();
    }//GEN-LAST:event_mostrarCatActionPerformed

    private void mostrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCliActionPerformed
        // TODO add your handling code here:
        TabCli MostrarCli = new TabCli();
        escritorio.add(MostrarCli);
        MostrarCli.show();
    }//GEN-LAST:event_mostrarCliActionPerformed

    private void mostrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProdActionPerformed
        // TODO add your handling code here:
        TabPro MostrarPro = new TabPro();
        escritorio.add(MostrarPro);
        MostrarPro.show();
    }//GEN-LAST:event_mostrarProdActionPerformed

    private void mostrarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEmpActionPerformed
        // TODO add your handling code here:
        TabEmp MostrarEmp = new TabEmp();
        escritorio.add(MostrarEmp);
        MostrarEmp.show();
    }//GEN-LAST:event_mostrarEmpActionPerformed

    private void mostrarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarVenActionPerformed
        // TODO add your handling code here:
        TabVent MostrarVent = new TabVent();
        escritorio.add(MostrarVent);
        MostrarVent.show();
    }//GEN-LAST:event_mostrarVenActionPerformed

    private void mostrarDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDvActionPerformed
        // TODO add your handling code here:
        TabDV MostrarDV = new TabDV();
        escritorio.add(MostrarDV);
        MostrarDV.show();
    }//GEN-LAST:event_mostrarDvActionPerformed

    private void mostrarAlmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlmpActionPerformed
        // TODO add your handling code here:
        TabAlmPro MostrarAP = new TabAlmPro();
        escritorio.add(MostrarAP);
        MostrarAP.show();
    }//GEN-LAST:event_mostrarAlmpActionPerformed

    private void mostrarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDisActionPerformed
        // TODO add your handling code here:
        TabDis MostrarDis = new TabDis();
        escritorio.add(MostrarDis);
        MostrarDis.show();
    }//GEN-LAST:event_mostrarDisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu1_Usuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mostarUsu;
    private javax.swing.JMenuItem mostrarAlmp;
    private javax.swing.JMenuItem mostrarCat;
    private javax.swing.JMenuItem mostrarCli;
    private javax.swing.JMenuItem mostrarDis;
    private javax.swing.JMenuItem mostrarDv;
    private javax.swing.JMenuItem mostrarEmp;
    private javax.swing.JMenuItem mostrarProd;
    private javax.swing.JMenuItem mostrarVen;
    // End of variables declaration//GEN-END:variables
}
