/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TabAlmPro extends javax.swing.JInternalFrame {
private CONEXIONN conn;
    /**
     * Creates new form TabAlmPro
     */
    public TabAlmPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_AlmPro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_TabAlmPro = new javax.swing.JButton();
        btn_Usuario1 = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_AlmPro.setBackground(new java.awt.Color(255, 255, 204));
        table_AlmPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_AlmPro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 345, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-producto.png"))); // NOI18N
        jLabel1.setText("Tabla almacen de productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_TabAlmPro.setBackground(new java.awt.Color(153, 255, 255));
        btn_TabAlmPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_TabAlmPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga-en-la-nube.png"))); // NOI18N
        btn_TabAlmPro.setText("CARGAR DATOS");
        btn_TabAlmPro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_TabAlmPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TabAlmProActionPerformed(evt);
            }
        });
        jPanel1.add(btn_TabAlmPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btn_Usuario1.setBackground(new java.awt.Color(0, 153, 102));
        btn_Usuario1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_Usuario1.setText("ACTUALIZAR");
        btn_Usuario1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Usuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 23, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TabAlmProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TabAlmProActionPerformed
        // TODO add your handling code here:
        conn =new CONEXIONN();
        CargarDatos();
       
    }//GEN-LAST:event_btn_TabAlmProActionPerformed

    private void btn_Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Usuario1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed
   public void CargarDatos(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("CODIGO");
        model.addColumn("FECHA INICIO");
        model.addColumn("Fecha vencimiento");
        model.addColumn("CODIGO DISTRIBUIDOR");
        
        ResultSet rs=conn.ObtenerDatos("SELECT CodAlm,FeiAlm,FevAlm,CodDis FROM almacenproductos");
        try{
            while(rs.next()){
                model.addRow(new Object[]{
                rs.getString("CodAlm"),
                rs.getString("FeiAlm"),
                rs.getString("FevAlm"),
                rs.getString("CodDis"),
            });
            }
             table_AlmPro.setModel(model);
        }catch(SQLException ex){
           ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TabAlmPro;
    private javax.swing.JButton btn_Usuario1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_AlmPro;
    // End of variables declaration//GEN-END:variables
}
